// Starts a dedicated server with a command generated by the tool itself and
// checks that the world file stores every modifier and checkbox it set.
// Usage: node tools/live-check.js <server-dir> [port]
//   server-dir: directory holding valheim_server.x86_64 (Linux build)
//   port:       game port for the throwaway world, default 2556
// Refuses to run while any valheim_server.x86_64 process is up, apart from
// leftovers of an earlier live check, which it kills first. The world is
// created in a temporary save directory that is removed afterwards.
const fs = require('fs');
const os = require('os');
const path = require('path');
const { spawn, execFileSync } = require('child_process');
const { loadApp, readVocabulary } = require('./load-app');

const serverDir = process.argv[2];
const port = process.argv[3] || '2556';
const READY = /Opened Steam server/;
const SAVED = /World save \(5\/5\) done/;
const START_TIMEOUT_MS = 5 * 60 * 1000;
const STOP_TIMEOUT_MS = 2 * 60 * 1000;

function fail(msg) {
  console.error(msg);
  process.exit(1);
}

if (!serverDir || !fs.existsSync(path.join(serverDir, 'valheim_server.x86_64'))) {
  fail('Usage: node tools/live-check.js <server-dir> [port], where server-dir holds valheim_server.x86_64');
}

// One live check per machine: a second one would take the first one's
// processes for leftovers below. The lock holds the owner's pid; a lock whose
// owner is no longer a live check (killed outright) is taken over.
const LOCK = path.join(os.tmpdir(), 'vwc-live.lock');
function lockOwnerAlive(pid) {
  try { return fs.readFileSync(`/proc/${pid}/cmdline`, 'utf8').includes('live-check.js'); } catch (e) { return false; }
}
function takeLock() {
  try {
    fs.writeFileSync(LOCK, String(process.pid), { flag: 'wx' });
    return true;
  } catch (e) {
    if (e.code !== 'EEXIST') throw e;
    return false;
  }
}
let locked = false;
for (let attempt = 0; attempt < 5 && !locked; attempt++) {
  if (takeLock()) { locked = true; break; }
  let owner;
  try { owner = fs.readFileSync(LOCK, 'utf8').trim(); } catch (e) {
    if (e.code === 'ENOENT') continue; // released in the meantime, try again
    throw e;
  }
  // An empty lock is being written by its owner right now.
  if (owner === '' || lockOwnerAlive(owner)) {
    if (owner !== '') fail(`Another live check (pid ${owner}) is running on this machine.`);
    execFileSync('sleep', ['0.2']);
    continue;
  }
  // Stale: move it aside atomically, so of two checks taking it over only one
  // moves this file. If what was moved is not the stale lock that was judged,
  // another check has taken the lock meanwhile: put it back and stop.
  const aside = `${LOCK}.stale-${process.pid}`;
  try { fs.renameSync(LOCK, aside); } catch (e) {
    if (e.code === 'ENOENT') continue;
    throw e;
  }
  const moved = fs.readFileSync(aside, 'utf8').trim();
  if (moved !== owner) {
    // Restores a lock that was still being written by its owner; if a newer
    // lock already sits at LOCK, the link fails and that one stays.
    try { fs.linkSync(aside, LOCK); } catch (e) { /* a newer lock is in place */ }
    fs.rmSync(aside, { force: true });
    fail('Another live check took over the lock at the same moment; not starting a second one.');
  }
  fs.rmSync(aside, { force: true });
}
if (!locked) fail('Could not take the live check lock; another live check is probably starting.');
process.on('exit', () => {
  try { if (fs.readFileSync(LOCK, 'utf8').trim() === String(process.pid)) fs.rmSync(LOCK); } catch (e) { /* gone */ }
});

// A cancelled job must not leave a server behind either. Installed before
// anything is created, so there is no window where a signal skips the clean-up
// (process.exit also runs the lock release above).
let work = null;
let child = null;
for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => {
    signal('SIGKILL');
    if (work) fs.rmSync(work, { recursive: true, force: true });
    process.exit(1);
  });
}

// A previous check that was killed outright (SIGKILL, OOM, host stop) had no
// chance to clean up. Its processes carry VWC_LIVE_CHECK=<its temp dir> in their
// environment, which only processes of this user can read, and its temp dir
// holds a marker file. Only those are killed and removed.
const MARKER_ENV = 'VWC_LIVE_CHECK';
const MARKER_FILE = '.vwc-live-check';
const WORK_PREFIX = path.join(os.tmpdir(), 'vwc-live-');
const killed = [];
for (const pid of fs.readdirSync('/proc').filter(p => /^\d+$/.test(p) && +p !== process.pid)) {
  let env;
  try { env = fs.readFileSync(`/proc/${pid}/environ`, 'utf8').split('\0'); } catch (e) { continue; }
  const tag = env.find(v => v.startsWith(MARKER_ENV + '='));
  if (tag && tag.slice(MARKER_ENV.length + 1).startsWith(WORK_PREFIX)) {
    try {
      const args = fs.readFileSync(`/proc/${pid}/cmdline`, 'utf8').split('\0').join(' ').trim();
      process.kill(+pid, 'SIGKILL');
      killed.push(pid);
      console.log(`Killed leftover process ${pid} from an earlier live check: ${args}`);
    } catch (e) { /* gone already */ }
  }
}
for (const d of fs.readdirSync(os.tmpdir()).filter(d => d.startsWith('vwc-live-'))) {
  const dir = path.join(os.tmpdir(), d);
  if (fs.existsSync(path.join(dir, MARKER_FILE))) fs.rmSync(dir, { recursive: true, force: true });
}
// Let the killed processes leave the process table before the check below.
for (let waited = 0; killed.some(pid => fs.existsSync(`/proc/${pid}`)) && waited < 30; waited++) {
  execFileSync('sleep', ['0.5']);
}

try {
  const pids = execFileSync('pidof', ['valheim_server.x86_64'], { encoding: 'utf8' }).trim();
  fail(`A dedicated server is already running (pid ${pids}); not starting a second one.`);
} catch (e) {
  if (e.code === 'ENOENT') fail('pidof is not installed; it is needed to detect a running dedicated server.');
  if (e.status !== 1) throw e; // pidof exits 1 when nothing matches
}

// Every modifier set to the last non-default value the server lists, every checkbox on.
const vocab = readVocabulary();
const { app, el } = loadApp();
const expected = {};
for (const [key, d] of Object.entries(app.SLIDERS)) {
  const name = d.arg || key;
  if (!(vocab.modifiers[name] || []).length) fail(`tools/server-vocabulary.json lists no values for modifier '${name}'`);
  const value = vocab.modifiers[name][vocab.modifiers[name].length - 1];
  const idx = d.values.indexOf(value);
  if (idx < 0 || idx === d.def) fail(`Slider ${key} cannot select server value '${value}'`);
  el('sl-' + key).value = String(idx);
  expected[name] = value;
}
for (const k of app.CHECKS) el(app.CHK_ID[k]).checked = true;
const WORLD_ORDER = ['combat', 'deathpenalty', 'resources', 'raids', 'portals'];
const unordered = Object.keys(expected).filter(n => !WORLD_ORDER.includes(n));
if (unordered.length || Object.keys(expected).length !== WORLD_ORDER.length) {
  fail(`Modifiers ${Object.keys(expected).join(', ')} do not match the world file's ${WORLD_ORDER.join(', ')}`);
}

work = fs.mkdtempSync(path.join(os.tmpdir(), 'vwc-live-'));
fs.writeFileSync(path.join(work, MARKER_FILE), '');
Object.assign(el('serverName'), { value: 'livecheck' });
Object.assign(el('worldName'), { value: 'livecheck' });
Object.assign(el('serverPort'), { value: port });
Object.assign(el('saveDir'), { value: path.join(work, 'save') });
Object.assign(el('saveInterval'), { value: '1800' });
Object.assign(el('backupCount'), { value: '4' });
Object.assign(el('backupShort'), { value: '7200' });
Object.assign(el('backupLong'), { value: '43200' });
const script = app.genLinux();
const scriptPath = path.join(work, 'start.sh');
fs.writeFileSync(scriptPath, script, { mode: 0o755 });
console.log(script.split('\n').filter(l => /-modifier|-setkey/.test(l)).map(l => l.trim()).join('\n'));

const logPath = path.join(work, 'server.log');
const logFd = fs.openSync(logPath, 'w');
child = spawn('bash', [scriptPath], {
  cwd: serverDir, stdio: ['ignore', logFd, logFd], detached: true,
  env: Object.assign({}, process.env, { [MARKER_ENV]: work })
});
fs.closeSync(logFd); // the child holds its own copy
let spawnError = null;
child.on('error', e => { spawnError = e; });
const log = () => fs.readFileSync(logPath, 'utf8');

function waitFor(re, ms) {
  return new Promise((resolve, reject) => {
    const started = Date.now();
    const timer = setInterval(() => {
      if (spawnError) { clearInterval(timer); reject(new Error(`could not start the server script: ${spawnError.message}`)); }
      else if (re.test(log())) { clearInterval(timer); resolve(); }
      else if (child.exitCode !== null) { clearInterval(timer); reject(new Error(`server exited early (code ${child.exitCode})`)); }
      else if (Date.now() - started > ms) { clearInterval(timer); reject(new Error(`timed out waiting for ${re}`)); }
    }, 1000);
  });
}

// Signal the whole process group: bash and the server it started.
function signal(sig) {
  if (!child) return;
  try { process.kill(-child.pid, sig); } catch (e) { /* already gone */ }
}
function groupAlive() {
  if (!child) return false;
  try { process.kill(-child.pid, 0); return true; } catch (e) { return false; }
}

// SIGINT lets the server save; anything still running after the grace period is killed.
async function shutDown(graceMs) {
  signal('SIGINT');
  const started = Date.now();
  while (groupAlive() && Date.now() - started < graceMs) await new Promise(r => setTimeout(r, 1000));
  if (groupAlive()) {
    signal('SIGKILL');
    while (groupAlive()) await new Promise(r => setTimeout(r, 200));
  }
}


function check() {
  const errors = [];
  const text = log();
  for (const line of text.split('\n')) {
    if (/Could not parse|Failed to parse key/.test(line)) errors.push('server log: ' + line.trim());
  }
  const worldDir = path.join(work, 'save', 'worlds_local', 'livecheck');
  // Saves are _main.<generation>.fwl2; take the highest generation.
  const generation = f => +((f.match(/\.(\d+)\.fwl2$/) || [])[1] || -1);
  const fwl = fs.readdirSync(worldDir).filter(f => f.endsWith('.fwl2')).sort((a, b) => generation(a) - generation(b)).pop();
  if (!fwl) return errors.concat(`no .fwl2 world file in ${worldDir}`);
  const data = fs.readFileSync(path.join(worldDir, fwl)).toString('latin1');
  const presets = data.match(/combat_\w+:deathpenalty_\w+:resources_\w+:raids_\w+:portals_\w+/g) || [];
  const stored = presets.pop();
  // The world file always lists the modifiers in this order, whatever order app.js uses.
  const want = WORLD_ORDER.map(n => `${n}_${expected[n]}`).join(':');
  console.log(`world file: ${stored || '(no modifier string)'}`);
  if (stored !== want) errors.push(`world file stores '${stored}', expected '${want}'`);
  for (const k of app.CHECKS) {
    // Keys are .NET strings with a 7-bit encoded length, one byte below 128.
    if (k.length >= 128) { errors.push(`checkbox key '${k}' is too long for the one-byte length match`); continue; }
    if (!data.includes(String.fromCharCode(k.length) + k)) errors.push(`world file has no '${k}' key`);
  }
  return errors;
}

(async () => {
  let errors;
  try {
    await waitFor(READY, START_TIMEOUT_MS);
    await shutDown(STOP_TIMEOUT_MS);
    if (!SAVED.test(log())) throw new Error('server stopped without logging a completed world save');
    errors = check();
  } catch (e) {
    await shutDown(10 * 1000);
    errors = [e.message];
  }
  if (errors.length) {
    console.error(errors.join('\n'));
    // The temporary directory is removed either way, so the log tail goes to the output.
    console.error('\nLast 60 lines of the server log:\n' + log().split('\n').slice(-60).join('\n'));
  }
  fs.rmSync(work, { recursive: true, force: true });
  if (errors.length) process.exit(1);
  console.log(`Live check passed against the server in ${serverDir}.`);
})();
